name: PixelgamesEconomySell
version: 2.4#
api: [3.0.0-ALPHA11]
main: Authors\PixelgamesEconomySell\PixelgamesEconomySell
author: onebone, iStrafeNubzHDyt
depend: [EconomyAPI]

commands:

 sell:
  description: Hauptbefehl von PixelgamesEconomySell zur Erstellung/Entfernung von Verkaufsständen
  usage: /sell <create|delete> [ItemID[:Meta]] [Menge] [Belohnung] [Ausrichtung]
  permission: pgeconomysell.command.sell;pgeconomysell.command.sell.create;pgeconomysell.command.sell.remove;
  
permissions:
 pgeconomysell:
  description: Erlaubt alle Funtionen in PixelgamesEconomySell
  default: op

  children:
   pgeconomysell.command.sell:
    description: Erlaubt die Benutzung von /sell

    children:
     pgeconomysell.command.sell.create:
      description: Erlaubt die Benutzung von /sell create

     pgeconomysell.command.sell.delete:
      description: Erlaubt die Benutzung von /sell delete

   pgeconomysell.sell.*:
    description: Erlaubt alle Funktionen bei Verkäufen
    default: op

    children:
     pgeconomysell.sell.sell:
      description: Erlaubt Spielern, Verkaufsstände zu nutzen
      default: true